"""
workflow_utils.py — Testable Python implementations of n8n Code-node logic.

These functions mirror the JavaScript inside n8n Code nodes so they can be:
  - Unit tested without a running n8n instance
  - Documented with type hints and clear semantics
  - Reused in replay/validation scripts

Each function corresponds to a specific Code node in one of the 11 workflows.
"""
from __future__ import annotations

import hashlib
import math
import re
from datetime import datetime, timezone
from typing import Any


# ──────────────────────────── Workflow 10: Error Handler ─────────────────────

def classify_error_severity(error_message: str) -> str:
    """
    Classify an error message into INFO / WARNING / CRITICAL.

    Mirrors: workflow 10, node "Code — Format Error"

    Rules (first match wins):
    - CRITICAL: timeout, connection refused, 401, 403, 5xx, fatal
    - WARNING:  rate limit, retry needed, 429, warn-level messages
    - INFO:     everything else
    """
    msg = str(error_message or "")
    if re.search(r"timeout|ECONNREFUSED|401|403|5\d\d|fatal", msg, re.I):
        return "CRITICAL"
    if re.search(r"rate|retry|warn|429", msg, re.I):
        return "WARNING"
    return "INFO"


# ──────────────────────────── Workflow 06: Warmth Decay ──────────────────────

def apply_warmth_decay(
    warmth: float,
    days_inactive: float,
    has_recent_reply: bool = False,
    reply_boost: int = 30,
    decay_rate: float = 0.9,
) -> int:
    """
    Compute new warmth score after applying daily decay.

    Mirrors: workflow 06, node "Code — Apply Warmth Decay"

    Formula:
        new_warmth = warmth * decay_rate ^ max(0, days_inactive)
        if has_recent_reply: new_warmth = min(100, new_warmth + reply_boost)

    Args:
        warmth: current warmth score (0-100)
        days_inactive: days since last activity
        has_recent_reply: True if the lead replied recently
        reply_boost: points added for a recent reply (default 30)
        decay_rate: daily decay multiplier (default 0.9 = ~10%/day)

    Returns:
        Rounded integer warmth score capped at 100.
    """
    decayed = warmth * math.pow(decay_rate, max(0.0, days_inactive))
    result = round(decayed)
    if has_recent_reply:
        result = min(100, result + reply_boost)
    return result


def warmth_to_bucket(warmth: int) -> str:
    """
    Classify warmth score into engagement bucket.

    Used to determine nurture cadence: hot leads get immediate follow-up,
    cold leads get long-gap or re-activation sequence.
    """
    if warmth >= 70:
        return "hot"
    if warmth >= 40:
        return "warm"
    if warmth >= 15:
        return "cool"
    return "cold"


# ──────────────────────────── Workflow 01: Idempotency ───────────────────────

def make_event_key(event_data: dict[str, Any], key_fields: list[str] | None = None) -> str:
    """
    Generate a deterministic idempotency key for an event.

    Mirrors the deduplication pattern used across multiple workflows:
    prevents duplicate processing of the same signal/lead/event.

    Args:
        event_data: the incoming event dict
        key_fields: fields to include in the key (default: id, source, timestamp)

    Returns:
        SHA-256 hex string (first 16 chars for readability).

    Example:
        >>> make_event_key({"id": "123", "source": "linkedin", "url": "..."})
        'a3f1...'
    """
    fields = key_fields or ["id", "source", "url", "company", "email"]
    parts = [str(event_data.get(f, "")) for f in fields]
    raw = "|".join(parts).encode("utf-8")
    return hashlib.sha256(raw).hexdigest()[:16]


def is_duplicate_event(
    event_key: str,
    processed_keys: set[str],
) -> bool:
    """
    Check if an event has already been processed.

    Idempotency gate: before processing a new event, call this to skip
    duplicates. If False (new event), caller should add key to processed_keys.

    Args:
        event_key: key generated by make_event_key()
        processed_keys: set of previously processed keys (from DB or cache)
    """
    return event_key in processed_keys


# ──────────────────────────── Workflow 03: Consensus ────────────────────────

def compute_consensus_score(
    scores: list[float],
    weights: list[float] | None = None,
) -> dict[str, Any]:
    """
    Compute weighted consensus from multiple LLM scores.

    Mirrors the scoring aggregation in workflow 03 (Multi-LLM Consensus).

    Args:
        scores: individual scores from each LLM (0.0–1.0)
        weights: optional weight per model (default: equal weights)

    Returns:
        dict with: score (float), agreement (bool), divergence (float)

    Agreement rule: True when max_score - min_score <= 0.3 (≤30% spread).
    """
    if not scores:
        return {"score": 0.0, "agreement": False, "divergence": 0.0}

    w = weights or [1.0] * len(scores)
    if len(w) != len(scores):
        raise ValueError("weights length must match scores length")

    total_weight = sum(w)
    weighted_sum = sum(s * wt for s, wt in zip(scores, w))
    consensus_score = weighted_sum / total_weight

    divergence = max(scores) - min(scores)
    agreement = divergence <= 0.3

    return {
        "score": round(consensus_score, 3),
        "agreement": agreement,
        "divergence": round(divergence, 3),
    }


# ──────────────────────────── Retry policy (documentation) ───────────────────

RETRY_POLICY = {
    "external_api": {
        "max_attempts": 3,
        "timeout_seconds": 30,
        "backoff_seconds": [5, 15, 45],
        "on_exhausted": "route_to_error_handler",
    },
    "llm_api": {
        "max_attempts": 2,
        "timeout_seconds": 60,
        "backoff_seconds": [10, 30],
        "on_exhausted": "route_to_human_review",
    },
    "webhook": {
        "max_attempts": 5,
        "timeout_seconds": 15,
        "backoff_seconds": [2, 5, 10, 30, 60],
        "on_exhausted": "log_and_skip",
    },
}
"""
Documented retry policy for external calls.

Applied via n8n node settings (Error Handling → Retry on Fail) and
the Global Error Handler (workflow 10) which catches exhausted retries.

Recovery path:
    1. First failure → auto-retry per policy above
    2. Exhausted retries → Global Error Handler (workflow 10)
    3. Error Handler → logs severity to Airtable ErrorLog
    4. CRITICAL errors → notify via Slack/email node
    5. Human can re-trigger from Command Center (workflow 08)
"""
